#if hasFeature(Embedded)
import CSQLite
import Logging

/// A wrapper for the `OpaquePointer` used to represent an open `sqlite3` handle.
///
/// On WASI the runtime is single-threaded, so no thread pool / locking is involved; the
/// `@unchecked Sendable` is justified the same way as the SwiftNIO build (serialized SQLite,
/// `SQLITE_OPEN_FULLMUTEX`), and the handle is only mutated to `nil` on close.
final class SQLiteConnectionHandle: @unchecked Sendable {
    var raw: OpaquePointer?

    init(_ raw: OpaquePointer?) {
        self.raw = raw
    }
}

/// A single open connection to an SQLite database (WASI / Embedded build).
///
/// This is the NIO-free variant: it exposes a Swift-Concurrency (`async`/`await`) API over CSQLite
/// with no `EventLoopFuture`, `EventLoopGroup`, or `NIOThreadPool`. Because WebAssembly is
/// single-threaded, the blocking libsqlite3 calls run inline on the calling task. The observable
/// hook API and connection pooling are not available on this build.
public final class SQLiteConnection: SQLiteDatabase, Sendable {
    /// The possible storage types for an SQLite database.
    public enum Storage: Equatable, Sendable {
        /// An SQLite database stored entirely in memory.
        case memory

        /// An SQLite database stored in a file at the specified path.
        case file(path: String)
    }

    /// Return the version of the embedded libsqlite3 as a 32-bit integer value.
    public static func libraryVersion() -> Int32 {
        sqlite_nio_sqlite3_libversion_number()
    }

    /// Return the version of the embedded libsqlite3 as a string.
    public static func libraryVersionString() -> String {
        String(cString: sqlite_nio_sqlite3_libversion())
    }

    // See `SQLiteDatabase.logger`.
    public let logger: Logger

    /// The underlying `sqlite3` connection handle.
    let handle: SQLiteConnectionHandle

    /// Initialize a new ``SQLiteConnection``. Internal use only.
    private init(handle: OpaquePointer?, logger: Logger) {
        self.handle = .init(handle)
        self.logger = logger
    }

    /// Returns the most recent error message from the connection as a string.
    var errorMessage: String? {
        sqlite_nio_sqlite3_errmsg(self.handle.raw).map { String(cString: $0) }
    }

    /// `false` if the connection is valid, `true` if not.
    public var isClosed: Bool {
        self.handle.raw == nil
    }

    /// Open a new connection to an SQLite database.
    ///
    /// - Parameters:
    ///   - storage: Specifies the location of the database for the connection. See ``Storage`` for details.
    ///   - logger: The logger used by the connection. Defaults to a new `Logger`.
    /// - Returns: A new connection object.
    public static func open(
        storage: Storage = .memory,
        logger: Logger = .init(label: "codes.vapor.sqlite")
    ) async throws -> SQLiteConnection {
        let path: String
        switch storage {
        case .memory: path = ":memory:"
        case .file(let file): path = file
        }

        var handle: OpaquePointer?
        let openOptions = SQLITE_OPEN_CREATE | SQLITE_OPEN_READWRITE | SQLITE_OPEN_FULLMUTEX | SQLITE_OPEN_URI | SQLITE_OPEN_EXRESCODE
        let openRet = sqlite_nio_sqlite3_open_v2(path, &handle, openOptions, nil)
        guard openRet == SQLITE_OK else {
            throw SQLiteError(reason: .init(statusCode: openRet), message: "Failed to open to SQLite database at \(path)")
        }

        let busyRet = sqlite_nio_sqlite3_busy_handler(handle, { _, _ in 1 }, nil)
        guard busyRet == SQLITE_OK else {
            sqlite_nio_sqlite3_close(handle)
            throw SQLiteError(reason: .init(statusCode: busyRet), message: "Failed to set busy handler for SQLite database at \(path)")
        }

        logger.debug("Connected to sqlite database", metadata: ["path": .string(path)])
        return SQLiteConnection(handle: handle, logger: logger)
    }

    /// Returns the last value generated by auto-increment functionality on this database.
    public func lastAutoincrementID() async throws -> Int {
        numericCast(sqlite_nio_sqlite3_last_insert_rowid(self.handle.raw))
    }

    /// Run the provided closure with this connection.
    public func withConnection<T>(
        _ closure: @escaping @Sendable (SQLiteConnection) async throws -> T
    ) async throws -> T {
        try await closure(self)
    }

    // See `SQLiteDatabase.query(_:_:logger:_:)`.
    public func query(
        _ query: String,
        _ binds: [SQLiteData],
        logger: Logger,
        _ onRow: @escaping @Sendable (SQLiteRow) -> Void
    ) async throws {
        var statement = try SQLiteStatement(query: query, on: self)
        let columns = try statement.columns()
        try statement.bind(binds)
        while let row = try statement.nextRow(for: columns) {
            onRow(row)
        }
    }

    /// Close the connection and invalidate its handle.
    public func close() async throws {
        sqlite_nio_sqlite3_close(self.handle.raw)
        self.handle.raw = nil
    }

    /// Install the provided ``SQLiteCustomFunction`` on the connection.
    public func install(customFunction: SQLiteCustomFunction) async throws {
        self.logger.trace("Adding custom function \(customFunction.name)")
        try customFunction.install(in: self)
    }

    /// Uninstall the provided ``SQLiteCustomFunction`` from the connection.
    public func uninstall(customFunction: SQLiteCustomFunction) async throws {
        self.logger.trace("Removing custom function \(customFunction.name)")
        try customFunction.uninstall(in: self)
    }

    deinit {
        assert(self.handle.raw == nil, "SQLiteConnection was not closed before deinitializing")
    }
}
#endif  // hasFeature(Embedded)
